# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  serializer:
    serialize_null: true
  param_fetcher_listener: true
  body_listener:
    enabled: true
    decoders:
      json: fos_rest.decoder.json
  format_listener:
    rules:
      - { path: ^/, priorities: [ json ], fallback_format: json, prefer_extension: true }

  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: validationErrors
  view:
    view_response_listener:  true