lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: "%env(JWT_TOKEN_TTL)%"


    # JWT Listeners
services:
    app.event.jwt_created_listener:
        class: App\EventListener\JWTAuthListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_invalid, method: onTokenFailure }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_not_found, method: onTokenFailure }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_expired, method: onTokenFailure }
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onTokenDecode }