vich_uploader:
    db_driver: orm

    mappings:
        article_images:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: true
            delete_on_remove: true
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_format: 'Y/m/d'
                    date_time_property: createdAt
        commercial_images:
            uri_prefix: /images/commercials
            upload_destination: '%kernel.project_dir%/public/images/commercials'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: true
            delete_on_remove: true
            delete_on_update: true