framework:
    cache:
        app: cache.adapter.redis
        system: cache.adapter.redis
        default_redis_provider: '%env(REDIS_CONNECTION)%'
        prefix_seed: "%env(REDIS_PREFIX)%"
        pools:
            doctrine.second_level_cache_pool:
                adapter: cache.app
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.query_cache_pool:
                adapter: cache.app