services:
    bus.handler.app.remove_chat:
        class: App\CommandBus\Chat\Remove\ChatRemoveCommandHandler
        autowire: true
        public: true
        tags:
            - { name: command_handler, handles: App\CommandBus\Chat\Remove\ChatRemoveCommand }

    bus.handler.app.article_create:
        class: App\CommandBus\Article\Create\ArticleCreateCommandHandler
        autowire: true
        public: true
        tags:
            - { name: command_handler, handles: App\CommandBus\Article\Create\ArticleCreateCommand }

    bus.handler.app.article_update:
        class: App\CommandBus\Article\Update\ArticleUpdateCommandHandler
        autowire: true
        public: true
        tags:
            - { name: command_handler, handles: App\CommandBus\Article\Update\ArticleUpdateCommand }

    bus.handler.app.contact_remove:
        class: App\CommandBus\Contact\Remove\ContactRemoveCommandHandler
        autowire: true
        public: true
        tags:
            - { name: command_handler, handles: App\CommandBus\Contact\Remove\ContactRemoveCommand }

    bus.handler.app.article_promote:
        class: App\CommandBus\Article\Promote\ArticlePromoteCommandHandler
        autowire: true
        public: true
        tags:
            - { name: command_handler, handles: \App\CommandBus\Article\Promote\ArticlePromoteCommand }

