nelmio_api_doc:
    documentation:
        info:
            title: Autobum
            description: Autobum APIs!
            version: 1.0.0
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Enter in value field "Bearer TOKEN_VALUE"'
                name: Authorization
                in: header
        security:
            - Bearer: []
        definitions:
            AccessToken:
                type: object
                properties:
                    token:
                        type: string
                        example: eyJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX01PQklMRV9VU0VSIl0sInVzZXJuYW1lIjoibWFya29AZ21haWwuY29tIiwiZmlyc3ROYW1lIjoiTWFya28iLCJsYXN0TmFtZSI6Ik1hcmtvdmljIiwiaWF0IjoxNTM2MTQ2MzYxLCJleHAiOjE1MzYxNDk5NjF9.dojRoZfbyJReIv6z275PbUudQE7Cy--43qgSwnFfJyjy2k3foFQIGi5nN-bWad5UMku9u-HPx6zK0E4QdSqRZZFc2RarR6iQkZWpWYnrIzWe2zFPoO2xGw1u5p77Pe2TMhGL4vCyTp93ABre40x49vESW8F-FLy6nycQQk6o2YZUVGmR5iSClWsWnK5yMvyOWOCwbhH2ecbQQE7gfcRnJ07KBqaW_2TMAPK8hABOpnTZHrB5JI2IyeHGbY2xbmE2ACwOtHIplDjswFtdGMLF2QTxLpYtuOg_5Qa_WSoV9vklNg7_cBtDkQiMxOrIgX9340FOySbsC6lxa2bFjjtqKA
                    refreshToken:
                        type: string
                        example: 21a185fcf0f318654166fec68370631c9f0bc223
            MetaPagination:
                type: object
                properties:
                    current:
                        type: number
                        example: 1
                    numItemsPerPage:
                        type: number
                        example: 10
                    pageCount:
                        type: number
                        example: 1
                    totalCount:
                        type: number
                        example: 3

    areas: # to filter documented areas
        path_patterns:
            - ^/(?!_profiler)(?!_wdt)(?!_error)(?!doc)(?!api/doc)
