# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    jwt_refresh_token_ttl: '%env(JWT_REFRESH_TOKEN_TTL)%'
    from_email: '%env(FROM_EMAIL)%'
    from_email_name: '%env(FROM_EMAIL_NAME)%'
    event_waiting_time: '%env(EVENTS_WAITING_TIME)%'
    frontend_url: '%env(FRONTEND_URL)%'
    security_question_answer: '%env(SECURITY_QUESTION_ANSWER)%'
    environment: '%env(APP_ENV)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $jwtRefreshTokenTTL: '%jwt_refresh_token_ttl%'
            $fromEmail: '%from_email%'
            $fromEmailName: '%from_email_name%'
            $eventWaitingTime: '%event_waiting_time%'
            $environment: '%environment%'

    app.doctrine.account_save_subscriber:
        class: App\EventSubscriber\SaveUserSubscriber
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    app.query_filter.query_filter_register:
        class: App\Helper\QueryFilter\QueryFilterRegister
        public: true
        calls:
            - [ addFilter, [ "@app.query_filter.like_filter" ] ]
            - [ addFilter, [ "@app.query_filter.equals_filter" ] ]
            - [ addFilter, [ "@app.query_filter.greater_than_filter" ] ]
            - [ addFilter, [ "@app.query_filter.is_null_filter" ] ]
            - [ addFilter, [ "@app.query_filter.in_filter" ] ]
            - [ addFilter, [ "@app.query_filter.has_one_filter" ] ]
            - [ addFilter, [ "@app.query_filter.has_many_filter" ] ]
            - [ addFilter, [ "@app.query_filter.less_than_filter" ] ]

    app.query_filter.like_filter:
        class: App\Helper\QueryFilter\Filters\LikeFilter

    app.query_filter.equals_filter:
        class: App\Helper\QueryFilter\Filters\EqualsFilter

    app.query_filter.greater_than_filter:
        class: App\Helper\QueryFilter\Filters\GreaterThanFilter

    app.query_filter.less_than_filter:
        class: App\Helper\QueryFilter\Filters\LessThanFilter

    app.query_filter.is_null_filter:
        class: App\Helper\QueryFilter\Filters\IsNullFilter

    app.query_filter.in_filter:
        class: App\Helper\QueryFilter\Filters\InFilter

    app.query_filter.has_one_filter:
        class: App\Helper\QueryFilter\Filters\HasOneFilter

    app.query_filter.has_many_filter:
        class: App\Helper\QueryFilter\Filters\HasManyFilter

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
